### ISSUE TITLE
updating

### ISSUE THREAD

**Issue by pigreco** [opengeoshub/HCMGIS#2]
the plugin appears every day in the update section

thx

**Comment by thangqd** [comment]
Please let me know more about this issue and how can I fix it? Thank you pigreco

**Comment by pigreco** [comment]
@thangqd 
Every day the plugin update warning appears in the plugin manager even if you do not need to update.

win 10 osgeo4w

**Comment by thangqd** [comment]
@pigreco Please show me a screenshot so that I know what exactly the problem is and how to fix it. Thank you

**Comment by pigreco** [comment]
@thangqd 
![image](https://user-images.githubusercontent.com/7631137/43120267-e2e2a4d0-8f19-11e8-8a1c-32ae7093720a.png)

**Comment by thangqd** [comment]
Because the HCMGIS plugin is updated frequently (the latest version is 18.7.10 -yy-m-day), so the QGIS Plugin Manager automatically list it in upgradeable section. You should try other frequent updated plugins to test the way that the Plugin Manager works. So in this case, you should update or uninstall HCMGIS plugin to prevent uncomfortable notifications.
Hope this helps!

**Comment by drpeter2000** [comment]
Same issue as pigreco:  always shows update available even immediately after upgrading/uninstalling/upgrading, etc.  Maybe the problem comes from the following: "Installed version	18.07.10
Available version	18.7.10"  Note the difference between 07 and 7 ...

**Comment by thangqd** [comment]
I got it and I'm going to fix in the next version
Thanks @drpeter2000
